### ISSUE TITLE
Favicon generation generates incorrect tag

### ISSUE THREAD

**Issue by fraktalize** [jitesoft/boilerplate-spa#3]
**Expected behaviour:**
Favicon should generate a `<link rel="shortcut icon" type="image/png" href="favicon.png">`-element inside of `<head>.`

**Actual behaviour:**
Favicon generates a meta tag: `<meta property="favicon" content="favicon.png">`

**Comment by fraktalize** [comment]
False alarm, I should test more before submitting new issues!!!!

**Comment by Johannestegner** [comment]
I have though  noticed issues with the meta generation, which I tracked to the html plugin for webpack.
It seems that (for example) og-tags requires the `meta` tag to have `property` and `content` instead of `name` and `content`. I will have to research this a bit more though...
